---
title: "Research projects"
output:
  html_document:
    css: "custom_page.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

I am involved in many research projects, most of which focus on the development and application of statistical methods for time series and spatial analyses. I enjoy collaborating with a variety of people, and particularly students and post-docs because I tend to learn a lot from those experiences.

### Multivariate state-space models

__Multivariate Autoregressive State-Space (MARSS) models__. [Eli Holmes](https://faculty.washington.edu/eeholmes/), [Eric Ward](https://faculty.washington.edu/warde/), and I have developed an [R package](https://cran.r-project.org/web/packages/MARSS/index.html) with a detailed [user’s guide](https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf) for analyzing a variety of multivariate time series problems under a maximum likelihood framework. Examples include movement tracking, dynamic linear models (DLM), dynamic factor analysis (DFA), and estimating community interactions & stability.

__Time-Varying Vector Autogressive State-Space (TVVARSS) models__. [Eric Ward](https://faculty.washington.edu/warde/), [Steve Katz](http://cahnrs.wsu.edu/soe/people/facultynstaff/stephenkatz/), and I have developed an [R package](https://github.com/nwfsc-timeseries/tvvarss) to fit a Bayesian version of the model developed by [Ives & Dakos (2012)](https://doi.org/10.1890/ES11-00347.1) that includes multiple forms of observation models. We are using it to examine changing species interactions and community stability in kelp forest ecosystems.

### Integrated populations models

__Skagit River steelhead__. I developed an IPM for a population of steelhead from the Skagit River to help biologists from the [Skagit River System Cooperative](http://skagitcoop.org/) and the [Washington Department of Fish & Wildlife](http://wdfw.wa.gov/) to examine the effects of hatchery releases and instream flows on steelhead production. You can find a detailed description of the methods [here](https://mdscheuerell.github.io/ASSESSOR/).

__Snake River Chinook__. [Eric Buhle](mailto:eric.buhle@noaa.gov), [Jim Thorson](https://sites.google.com/site/thorsonresearch/), and I have developed an [R package](https://github.com/ebuhle/salmonIPM) to fit a Bayesian IPM to multiple populations that also includes broodstock removals for hatchery operations and the effects of hatchery-origin fish spawning in the wild. We are using the model to conduct population viability assessments and evaluate possible effects of various harvest control rules.


### Joint dynamic species density models

I have been working with [Jim Thorson](https://sites.google.com/site/thorsonresearch/) and several others on a variety of applications of joint dynamic species density models (JDSDM) to marine and terrestrial fauna. You can learn more about the models, applications, and __R__ packages at the [FishStats](https://james-thorson.github.io//) website.

